name: Traffic Analysis CI

on: # Triggers: run all jobs when a push or pull request happens at sql_projects/traffic_analysis/
  push:
    paths:
      - "sql_projects/traffic_analysis/**"
      - ".github/workflows/traffic_analysis_ci.yaml"
  pull_request:
    paths:
      - "sql_projects/traffic_analysis/**"
      - ".github/workflows/traffic_analysis_ci.yaml"

jobs: # Jobs: each defines a list of actions to execute. Job success => changes accepted, job failure => changes rejected
  test:
    runs-on: ubuntu-latest

    defaults: # Set default args
      run: # Every run: command in this job executes from this directory.
        working-directory: sql_projects/traffic_analysis

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install project
        run: pip install .[dev]

      - name: Check formatting
        run: black --check .

      - name: Check imports
        run: isort --check-only .

      - name: Run tests
        run: pytest